package devisecrypto

import (
	"encoding/json"
	"errors"
	"os"
	"os/exec"
	"strconv"
	"strings"
	"testing"

	"golang.org/x/crypto/bcrypt"
)

// testCost is the cheapest cost Digest accepts; these tests are about bytes,
// not work factor.
const testCost = MinStretches

type fixture struct {
	Name      string `json:"name"`
	Password  string `json:"password"`
	Pepper    string `json:"pepper"`
	Stretches int    `json:"stretches"`
	Hash      string `json:"hash"`
}

type fixtureFile struct {
	GeneratedBy string    `json:"generated_by"`
	Fixtures    []fixture `json:"fixtures"`
}

// mustDigest goes through the public API, so it pays the MinStretches floor.
// Use it only where Digest itself is what is under test.
func mustDigest(tb testing.TB, password string, cost int, pepper string) string {
	tb.Helper()

	hash, err := Digest(password, cost, pepper)
	if err != nil {
		tb.Fatalf("Digest(%q, %d, %q): %v", password, cost, pepper, err)
	}

	return hash
}

// cheapHash builds a hash to compare against at bcrypt's own minimum cost,
// which is roughly 60x faster than the MinStretches floor Digest enforces.
// Compare has no floor, so tests that only need something to verify against
// should use this rather than pay for a realistic work factor.
func cheapHash(tb testing.TB, input []byte) string {
	tb.Helper()

	hash, err := bcrypt.GenerateFromPassword(input, bcrypt.MinCost)
	if err != nil {
		tb.Fatalf("bcrypt.GenerateFromPassword(%q): %v", input, err)
	}

	return string(hash)
}

func loadFixtures(t *testing.T) fixtureFile {
	t.Helper()

	raw, err := os.ReadFile("testdata/devise_hashes.json")
	if err != nil {
		t.Fatalf("read fixtures: %v", err)
	}

	var parsed fixtureFile
	if err := json.Unmarshal(raw, &parsed); err != nil {
		t.Fatalf("parse fixtures: %v", err)
	}

	if len(parsed.Fixtures) == 0 {
		t.Fatal("fixture file is empty; run script/generate_fixtures.rb")
	}

	return parsed
}

// TestCompareAgainstRubyFixtures is the real compatibility check: every hash
// here came out of the Ruby bcrypt gem via script/generate_fixtures.rb.
func TestCompareAgainstRubyFixtures(t *testing.T) {
	t.Parallel()

	parsed := loadFixtures(t)
	t.Logf("fixtures generated by %s", parsed.GeneratedBy)

	for _, f := range parsed.Fixtures {
		t.Run(f.Name, func(t *testing.T) {
			ok, err := CompareErr(f.Password, f.Pepper, f.Hash)
			if err != nil {
				t.Fatalf("CompareErr returned %v", err)
			}
			if !ok {
				t.Errorf("Go rejected a hash Ruby produced for password %q pepper %q", f.Password, f.Pepper)
			}
		})
	}
}

// TestRubyFixturesRejectWrongPassword guards against a Compare that accepts
// anything, which would make the test above pass for the wrong reason.
func TestRubyFixturesRejectWrongPassword(t *testing.T) {
	t.Parallel()

	for _, f := range loadFixtures(t).Fixtures {
		t.Run(f.Name, func(t *testing.T) {
			// Prepend, not append: a password already at the 72-byte limit is
			// unchanged by trailing bytes, so appending would be a no-op.
			if Compare("x"+f.Password, f.Pepper, f.Hash) {
				t.Error("a modified password matched the Ruby hash")
			}
		})
	}
}

// TestGoHashesVerifyInRuby closes the loop in the other direction. Skipped
// when Ruby or the bcrypt gem is missing, so CI without Ruby still passes.
func TestGoHashesVerifyInRuby(t *testing.T) {
	t.Parallel()

	if _, err := exec.LookPath("ruby"); err != nil {
		t.Skip("ruby not installed")
	}
	if err := exec.Command("ruby", "-e", "require 'bcrypt'").Run(); err != nil {
		t.Skip("bcrypt gem not installed")
	}

	source := loadFixtures(t)
	var produced fixtureFile

	for _, f := range source.Fixtures {
		hash := mustDigest(t, f.Password, testCost, f.Pepper)
		produced.Fixtures = append(produced.Fixtures, fixture{
			Name:     f.Name,
			Password: f.Password,
			Pepper:   f.Pepper,
			Hash:     hash,
		})
	}

	payload, err := json.Marshal(produced)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}

	cmd := exec.Command("ruby", "script/verify_go_hashes.rb")
	cmd.Stdin = strings.NewReader(string(payload))

	output, err := cmd.CombinedOutput()
	t.Logf("ruby output:\n%s", output)

	if err != nil {
		t.Errorf("Ruby rejected at least one Go hash: %v", err)
	}
}

func TestDigest(t *testing.T) {
	t.Parallel()

	t.Run("is salted", func(t *testing.T) {
		first := mustDigest(t, "changeme", testCost, "a bad pepper")
		second := mustDigest(t, "changeme", testCost, "a bad pepper")

		if first == second {
			t.Errorf("identical inputs produced the same hash %q; the salt is not random", first)
		}
	})

	// Devise stores $2a$ hashes, so a Rails app must be able to read ours.
	t.Run("emits the 2a variant", func(t *testing.T) {
		hash := mustDigest(t, "changeme", testCost, "")
		if !strings.HasPrefix(hash, "$2a$") {
			t.Errorf("hash %q does not use the $2a$ variant Devise writes", hash)
		}
	})

	// Below MinStretches the two libraries pick different substitutes in
	// silence, so Digest refuses instead of guessing. See ErrStretchesOutOfRange.
	t.Run("rejects a cost outside the accepted range", func(t *testing.T) {
		for _, cost := range []int{-1, 0, 1, bcrypt.MinCost, MinStretches - 1, MaxStretches + 1} {
			t.Run(strconv.Itoa(cost), func(t *testing.T) {
				hash, err := Digest("changeme", cost, "")
				if !errors.Is(err, ErrStretchesOutOfRange) {
					t.Errorf("err = %v, want ErrStretchesOutOfRange", err)
				}
				if hash != "" {
					t.Errorf("a rejected cost must not return a hash, got %q", hash)
				}
			})
		}
	})

	// Only the lower bound is hashed. MaxStretches is 2^31 rounds and would
	// never finish, and DefaultStretches would cost 4.9x to prove the same
	// round trip.
	t.Run("uses the cost it is given", func(t *testing.T) {
		got, err := bcrypt.Cost([]byte(mustDigest(t, "changeme", MinStretches, "")))
		if err != nil {
			t.Fatal(err)
		}
		if got != MinStretches {
			t.Errorf("hash cost = %d, want %d", got, MinStretches)
		}

		if DefaultStretches < MinStretches || DefaultStretches > MaxStretches {
			t.Errorf("DefaultStretches %d is outside the accepted range", DefaultStretches)
		}
	})

	// The silent substitution the validation exists to prevent. Executable
	// proof of the divergence table in the README.
	t.Run("raw bcrypt still substitutes a low cost", func(t *testing.T) {
		raw, err := bcrypt.GenerateFromPassword([]byte("changeme"), bcrypt.MinCost-1)
		if err != nil {
			t.Fatalf("x/crypto now rejects a low cost, got %v", err)
		}

		cost, err := bcrypt.Cost(raw)
		if err != nil {
			t.Fatal(err)
		}
		if cost != bcrypt.DefaultCost {
			t.Errorf("cost = %d, want the x/crypto default %d", cost, bcrypt.DefaultCost)
		}
	})
}

// TestCompareIgnoresMinStretches is the other half of the cost decision:
// Digest refuses a weak cost, but Compare must still verify hashes a Rails
// app already stored below it. The Ruby fixtures are generated at cost 4
// precisely so this is exercised on every run.
func TestCompareIgnoresMinStretches(t *testing.T) {
	t.Parallel()

	var lowCost int

	for _, f := range loadFixtures(t).Fixtures {
		if f.Stretches >= MinStretches {
			continue
		}
		lowCost++

		if !Compare(f.Password, f.Pepper, f.Hash) {
			t.Errorf("%s: Compare rejected a cost %d hash; legacy logins would break", f.Name, f.Stretches)
		}
	}

	if lowCost == 0 {
		t.Fatalf("no fixture below cost %d, so this test proves nothing", MinStretches)
	}
	t.Logf("verified %d fixtures below cost %d", lowCost, MinStretches)
}

func TestCompare(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name string
		// The hash under test is built from digestPassword and digestPepper,
		// then probed with password and pepper.
		digestPassword, digestPepper string
		password, pepper             string
		want                         bool
	}{
		{name: "same password and pepper", digestPassword: "changeme", digestPepper: "a bad pepper", password: "changeme", pepper: "a bad pepper", want: true},
		{name: "wrong password", digestPassword: "other", digestPepper: "p", password: "changeme", pepper: "p", want: false},
		{name: "wrong pepper", digestPassword: "changeme", digestPepper: "q", password: "changeme", pepper: "p", want: false},
		{name: "pepper added later", digestPassword: "changeme", digestPepper: "", password: "changeme", pepper: "p", want: false},
		{name: "pepper dropped later", digestPassword: "changeme", digestPepper: "p", password: "changeme", pepper: "", want: false},
		{name: "password is the pepper", digestPassword: "changeme", digestPepper: "p", password: "changemep", pepper: "", want: true},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			hash := cheapHash(t, peppered(c.digestPassword, c.digestPepper))

			if got := Compare(c.password, c.pepper, hash); got != c.want {
				t.Errorf("Compare = %v, want %v", got, c.want)
			}
		})
	}
}

// TestCompareBlankHash covers a user row with no password set, or a blank
// hash string (e.g. whitespace), matching Rails Devise's hashed_password.blank?
// guard. A blank hash is an ordinary Devise state, not a corrupt hash, so it
// must never match and must not be reported as an error.
func TestCompareBlankHash(t *testing.T) {
	t.Parallel()

	for _, hash := range []string{"", " ", "   ", "\t", "\n", " \t\r\n "} {
		t.Run(strconv.Quote(hash), func(t *testing.T) {
			ok, err := CompareErr("changeme", "a bad pepper", hash)
			if ok {
				t.Error("a blank hash must never match")
			}
			if err != nil {
				t.Errorf("a blank hash is not an error, got %v", err)
			}
			if Compare("changeme", "a bad pepper", hash) {
				t.Error("Compare must return false for a blank hash")
			}
		})
	}
}

// TestNullByteRejected verifies that passwords or peppers containing null
// bytes are rejected with ErrNullByte. Ruby's bcrypt gem raises ArgumentError
// on null bytes, so we refuse them to avoid producing or verifying credentials
// Devise cannot handle.
func TestNullByteRejected(t *testing.T) {
	t.Parallel()

	dummyHash := cheapHash(t, []byte("password"))

	cases := []struct {
		name     string
		password string
		pepper   string
	}{
		{"null in password prefix", "\x00changeme", "pepper"},
		{"null in password middle", "change\x00me", "pepper"},
		{"null in password suffix", "changeme\x00", "pepper"},
		{"null in pepper prefix", "changeme", "\x00pepper"},
		{"null in pepper middle", "changeme", "pep\x00per"},
		{"null in pepper suffix", "changeme", "pepper\x00"},
		{"null alone", "\x00", ""},
		{"null alone in pepper", "", "\x00"},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			_, err := Digest(c.password, testCost, c.pepper)
			if !errors.Is(err, ErrNullByte) {
				t.Errorf("Digest(%q, %q) err = %v, want ErrNullByte", c.password, c.pepper, err)
			}

			ok, err := CompareErr(c.password, c.pepper, dummyHash)
			if ok {
				t.Errorf("CompareErr(%q, %q) matched unexpectedly", c.password, c.pepper)
			}
			if !errors.Is(err, ErrNullByte) {
				t.Errorf("CompareErr(%q, %q) err = %v, want ErrNullByte", c.password, c.pepper, err)
			}

			if Compare(c.password, c.pepper, dummyHash) {
				t.Errorf("Compare(%q, %q) returned true, want false", c.password, c.pepper)
			}
		})
	}

	t.Run("blank hash takes precedence over null check in CompareErr", func(t *testing.T) {
		// Devise returns false if hashed_password.blank? before inspecting secret.
		ok, err := CompareErr("foo\x00bar", "pepper", "")
		if ok || err != nil {
			t.Errorf("CompareErr with blank hash and null password should be (false, nil), got (%v, %v)", ok, err)
		}
	})
}

func TestCompareErrMalformedHash(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name, hash string
	}{
		{"not a hash", "not a hash"},
		{"prefix only", "$2a$"},
		{"truncated", "$2a$04$tooshort"},
		{"unknown algorithm", "$9z$04$HfVeA4fospZ2U64CklJJu.xycNBCf.vwTcBBZvSSlyxw.RqD9G9Ky"},
		{"non numeric cost", "$2a$zz$HfVeA4fospZ2U64CklJJu.xycNBCf.vwTcBBZvSSlyxw.RqD9G9Ky"},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			ok, err := CompareErr("changeme", "", c.hash)
			if ok {
				t.Error("a malformed hash matched")
			}
			if err == nil {
				t.Error("CompareErr should report why a malformed hash failed")
			}
			// Compare hides the error but must still refuse the hash.
			if Compare("changeme", "", c.hash) {
				t.Error("Compare matched a malformed hash")
			}
		})
	}
}

// TestCompare2bPrefix covers hashes written by other bcrypt implementations.
// $2a$ and $2b$ differ only in a length edge case bcrypt-ruby never hits, so
// swapping the prefix leaves a hash that must still verify.
func TestCompare2bPrefix(t *testing.T) {
	t.Parallel()

	for _, f := range loadFixtures(t).Fixtures {
		t.Run(f.Name, func(t *testing.T) {
			hash := "$2b$" + strings.TrimPrefix(f.Hash, "$2a$")
			if hash == f.Hash {
				t.Fatalf("fixture %q is not a $2a$ hash", f.Hash)
			}

			ok, err := CompareErr(f.Password, f.Pepper, hash)
			if err != nil {
				t.Fatalf("CompareErr returned %v", err)
			}
			if !ok {
				t.Error("a $2b$ hash of the same digest was rejected")
			}
		})
	}
}

// TestTruncation documents the deliberate choice to cut at 72 bytes rather
// than return bcrypt.ErrPasswordTooLong, so Rails-era logins keep working.
func TestTruncation(t *testing.T) {
	t.Parallel()

	long := strings.Repeat("a", 100)

	// Digest itself must not reject the long password; that is the decision
	// under test. The comparisons below run against a cheap hash instead.
	if _, err := Digest(long, MinStretches, ""); err != nil {
		t.Fatalf("Digest must not fail on a long password, got %v", err)
	}

	hash := cheapHash(t, peppered(long, ""))

	if !Compare(strings.Repeat("a", MaxPasswordBytes), "", hash) {
		t.Error("the first 72 bytes should match, since bcrypt ignores the rest")
	}

	if Compare(strings.Repeat("a", MaxPasswordBytes-1), "", hash) {
		t.Error("71 bytes must not match a 72-byte hash")
	}

	t.Run("pepper crosses the limit", func(t *testing.T) {
		password, pepper := strings.Repeat("b", 60), strings.Repeat("c", 20)

		hash := cheapHash(t, peppered(password, pepper))
		if !Compare(password, pepper, hash) {
			t.Error("truncated round trip failed")
		}
	})

	// Proves the truncation is load bearing, not luck: without it Digest
	// would fail here. If this ever stops erroring, peppered can be simplified.
	t.Run("raw bcrypt still rejects what we truncate", func(t *testing.T) {
		_, err := bcrypt.GenerateFromPassword([]byte(long), testCost)
		if !errors.Is(err, bcrypt.ErrPasswordTooLong) {
			t.Errorf("x/crypto no longer returns ErrPasswordTooLong, got %v", err)
		}
	})
}

// TestBlankPepperIsDropped mirrors Devise's pepper.present? guard, which
// treats a whitespace-only pepper as no pepper at all.
func TestBlankPepperIsDropped(t *testing.T) {
	t.Parallel()

	hash := cheapHash(t, []byte("changeme"))

	for _, pepper := range []string{"", " ", "   ", "\t", "\n", " \t\r\n "} {
		t.Run(strconv.Quote(pepper), func(t *testing.T) {
			if !Compare("changeme", pepper, hash) {
				t.Error("a blank pepper must be ignored, like Devise's present? check")
			}
		})
	}
}

// FuzzDigestCompare exercises the peppering and truncation logic, which is
// the only part of this package that can disagree with Devise. It calls
// bcrypt at MinCost directly rather than through Digest: Digest now enforces
// MinStretches, and at cost 10 each execution would take about 110ms, which
// would cut the fuzzer to roughly nine cases per second.
func FuzzDigestCompare(f *testing.F) {
	f.Add("changeme", "a bad pepper")
	f.Add("", "")
	f.Add(strings.Repeat("a", 100), strings.Repeat("b", 30))
	f.Add("pässwörd✓", "pépper")
	f.Add(strings.Repeat("a", MaxPasswordBytes), " ")

	f.Fuzz(func(t *testing.T, password, pepper string) {
		input := peppered(password, pepper)

		if len(input) > MaxPasswordBytes {
			t.Fatalf("peppered returned %d bytes for password %q pepper %q", len(input), password, pepper)
		}

		hash, err := bcrypt.GenerateFromPassword(input, bcrypt.MinCost)
		if err != nil {
			t.Fatalf("bcrypt refused peppered output for password %q pepper %q: %v", password, pepper, err)
		}

		// A null byte in password or pepper is refused by Digest and CompareErr.
		if strings.IndexByte(password, 0) != -1 || strings.IndexByte(pepper, 0) != -1 {
			if _, err := Digest(password, MinStretches, pepper); !errors.Is(err, ErrNullByte) {
				t.Fatalf("Digest(%q, %q) err = %v, want ErrNullByte", password, pepper, err)
			}
			ok, err := CompareErr(password, pepper, string(hash))
			if ok || !errors.Is(err, ErrNullByte) {
				t.Fatalf("CompareErr(%q, %q) err = %v, want ErrNullByte", password, pepper, err)
			}
			return
		}

		// Compare must rebuild the identical input from the same arguments.
		ok, err := CompareErr(password, pepper, string(hash))
		if err != nil {
			t.Fatalf("CompareErr failed: %v", err)
		}
		if !ok {
			t.Errorf("round trip failed for password %q pepper %q", password, pepper)
		}
	})
}

// FuzzCompareErr exercises Compare and CompareErr with arbitrary password,
// pepper, and hashedPassword strings to ensure malformed, corrupted, or
// hostile hash inputs never trigger panics or unexpected errors.
func FuzzCompareErr(f *testing.F) {
	f.Add("changeme", "a bad pepper", "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy")
	f.Add("", "", "")
	f.Add("password", "", "not-a-valid-bcrypt-hash")
	f.Add("password", "pepper", "$2a$00$invalidcoststringthatislongenough")
	f.Add("password\x00extra", "pepper", "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy")
	f.Add("password", "pepper\x00extra", "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy")
	f.Add("changeme", "pepper", "   ")
	f.Add(strings.Repeat("a", 100), strings.Repeat("b", 100), strings.Repeat("c", 100))

	f.Fuzz(func(t *testing.T, password, pepper, hashedPassword string) {
		// Compare and CompareErr must never panic on arbitrary input.
		okErr, err := CompareErr(password, pepper, hashedPassword)
		ok := Compare(password, pepper, hashedPassword)

		if ok != okErr {
			t.Fatalf("Compare (%v) != CompareErr boolean (%v) for hash %q", ok, okErr, hashedPassword)
		}

		if strings.TrimSpace(hashedPassword) == "" {
			if err != nil {
				t.Fatalf("expected nil error on blank hash, got %v", err)
			}
			if ok {
				t.Fatalf("Compare must return false on blank hash")
			}
			return
		}

		if strings.IndexByte(password, 0) != -1 || strings.IndexByte(pepper, 0) != -1 {
			if !errors.Is(err, ErrNullByte) {
				t.Fatalf("expected ErrNullByte, got %v", err)
			}
			if ok {
				t.Fatalf("Compare must return false on null byte input")
			}
			return
		}
	})
}

func BenchmarkDigest(b *testing.B) {
	for _, cost := range []int{MinStretches, DefaultStretches} {
		b.Run("cost="+strconv.Itoa(cost), func(b *testing.B) {
			for b.Loop() {
				if _, err := Digest("changeme", cost, "a bad pepper"); err != nil {
					b.Fatal(err)
				}
			}
		})
	}
}

func BenchmarkCompare(b *testing.B) {
	for _, cost := range []int{MinStretches, DefaultStretches} {
		b.Run("cost="+strconv.Itoa(cost), func(b *testing.B) {
			hash := mustDigest(b, "changeme", cost, "a bad pepper")

			for b.Loop() {
				if !Compare("changeme", "a bad pepper", hash) {
					b.Fatal("unexpected mismatch")
				}
			}
		})
	}
}
